## Append samples of your project ##
resources:
- flowc.io_v1alpha1_gateway.yaml
- flowc.io_v1alpha1_listener.yaml
- flowc.io_v1alpha1_api.yaml
- flowc.io_v1alpha1_deployment.yaml
- flowc.io_v1alpha1_gatewaypolicy.yaml
- flowc.io_v1alpha1_apipolicy.yaml
- flowc.io_v1alpha1_backendpolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
